root = "."
tmp_dir = ".air"

[build]
cmd = "go build -buildvcs=true -o .air/main ./cmd/api"
bin = ".air/main"
include_dir = ["cmd", "internal", "pkg"]
include_ext = ["go", "tpl", "tmpl", "html", "sum", "env", "json", "yml"]
exclude_unchanged = true
exclude_regex = [".null-ls*"]
kill_delay = "1000ms"
delay = 1000
send_interrupt = true
follow_symlink = true
stop_on_error = false

[log]
main_only = true
time = true
